dist: xenial
addons:
  snaps:
    - name: dotnet-sdk
      confinement: classic
      channel: latest/beta
sudo: required
dotnet: 3.1.202
language: csharp
solution: OnlineBookingSystem.sln
mono: none
script:
  - dotnet restore ./OnlineBookingSystem.sln
  - sudo snap alias dotnet-sdk.dotnet dotnet
deploy:
 provider: azure_web_apps
 skip_cleanup: true
	